### ISSUE TITLE
unable to connect to mongodb

### ISSUE THREAD

**Issue by aoighost** [nartc/nest-mean#12]
It's undocumented how to configure the mongodb connection and I can't figure out how  to connect to it. I tried changing the configs according to an earlier issue and it won't connect.

**Comment by aoighost** [comment]
this was the issue I based my configs on, it didn't work
https://github.com/nartc/nest-mean/issues/5

**Comment by nartc** [comment]
Can I see your configuration file? and your Configuration module/service and AppModule? Thanks

**Comment by aoighost** [comment]
configuration service/module is from git. So is appmodule. Here is my config. Note this is all being run from docker compose

`{ "JWT_KEY": "MySecret!123", "MONGO_URI": "mongodb://localhost:27017/meantest", "PORT": "3000", "HOST": "localhost" }`

**Comment by nartc** [comment]
@aoighost if you're running inside of Docker, then your MONGO_URI cannot be localhost but whatever the name you give to mongo container in docker_compose.

**Comment by aoighost** [comment]
Yep, that was it. Thanks!
