### ISSUE TITLE
A typo in the server/shared/utilities folder name.

### ISSUE THREAD

**Issue by vpavlov80** [nartc/nest-mean#2]
First of thank you for the great tutorial. While I was going through it I found a typo in one of the folder names - `/server/src/shared/utitlies/` should be `/server/src/shared/utilities/` I believe. The issue is not breaking the code, because of the autoimport and thus is a bit hard to find.
- [x] Fix typo

**Comment by nartc** [comment]
Thank you! I'll make the necessary change 💃
