### ISSUE TITLE
JWT_KEY not defined error in server

### ISSUE THREAD

**Issue by jfey** [nartc/nest-mean#28]
Starting the server via npm run start leads to the following error:

[Nest] 79352   - 2020-02-12 18:43   [ExceptionHandler] Configuration property "JWT_KEY" is not defined +4ms

**Comment by riazosama** [comment]
Have you found the solution?

**Comment by kenzik** [comment]
That indicates that the configuration property is not available to the app. The app requires a few. Read the source. To provide it, add it to your environment:

```PORT=3030 MONGO_URI=mongodb://localhost:27017/yourdb HOST=localhost JWT_KEY=changeme npm start```

**Comment by nartc** [comment]
Please check #32
