### ISSUE TITLE
SERVER TODO: Upgrade to current packages/Refactor

### ISSUE THREAD

**Issue by kenzik** [nartc/nest-mean#29]
Refactor items I found:

- Swagger. This looks like a simple copy/paste
- typegoose (unmaintained) to @typegoose/typegoose
- Change to your new automapper

I gave the changes a go but got hungup on the automapper changes, and then realized that's yours too. Figured I'd just ask... 

Do you have time to npm-upgrade the server packages and give this a go in a new branch? I bet it'll only take you a quick minute, since you are so close to everything.

**Comment by nartc** [comment]
@kenzik Hi, thank you for the issue. I consider this repo as archived myself since I'm working on an updated MEAN tutorial with all the latest packages. However, due to Angular 9 + Nest 7 releases and they're still releasing patches, it slows things down a little bit for me. Please stay tuned :)
