### ISSUE TITLE
Type not assignable to type void

### ISSUE THREAD

**Issue by hfournier** [nartc/nest-mean#7]
In base.service.ts the return line in clearCollection(), gives:
Type '{ ok?: number; n?: number; }' is not assignable to type 'void'.ts(2322)
I copy and pasted that section of the code from here to make sure there were no mistakes.
@nestjs 5.7.3
typegoose 5.5.0
typescript 3.3.3

**Comment by hfournier** [comment]
Got rid of the error by changing the code to:
`    async clearCollection(filter = {}): Promise<{ ok?: number, n?: number }> {
        return this._model.deleteMany(filter).exec();
    }
`

**Comment by nartc** [comment]
@hfournier I believe that’s due to newer version of mongoose :)

**Comment by aoighost** [comment]
I just got the same error. Can this fix be put in upstream?

**Comment by nartc** [comment]
@aoighost Just updated the repo with the latest version of NestJS. Check out the commit log.
