### ISSUE TITLE
error TS2304: Cannot find name 'T'

### ISSUE THREAD

**Issue by fea17e86** [nartc/nest-mean#8]
Hi

In src/api/models/base.model.ts(4,6) `@pre` is used with the generic type `T`:

https://github.com/nartc/nest-mean/blob/9730cd95b8937344e8c7e172051df2519ef88bbe/server/src/shared/base.model.ts#L15

Typescript reports the error `src/api/models/base.model.ts(4,6): error TS2304: Cannot find name 'T'.` Is there a fix for that?

**Comment by DouglasWebster** [comment]
I just replaced
   `@pre<T>('findOneAndUpdate', fuction() { ...`

with

   `@pre<any>('findOneAndUpdate', fuction() { ...`

and so far it seems to work OK.

**Comment by cesar3030** [comment]
I Have the same problem as well :/

**Comment by nartc** [comment]
@fea17e86  @cesar3030  You can just remove the generic. I  put the generic there because it was required at the time I made this tutorial. But it seems that it's no longer required.

**Comment by cesar3030** [comment]
@nartc Thank you!
