### ISSUE TITLE
[TS Lint Error] Array type using "T[]" is forbidden?

### ISSUE THREAD

**Issue by emjimadhu** [nartc/nest-mean#9]
I am trying to create  the base service. But i get tslint error. this is the method

```
async findAll(
    filter = {},
    selectFields: {}
  ): Promise<InstanceType<T>[]> {
    if (selectFields) {
      return this.model.find(filter).select(selectFields).exec();
    } else {
      return this.model.find(filter).exec();
    }
  }
```

**Comment by nartc** [comment]
I think that's a new TSLint rule for complex type or something. Can you try: `Array<InstanceType<T>>`?

**Comment by emjimadhu** [comment]
After this i am getting two errors.

The first error is on `InstanceType of T`

![Screenshot 2019-07-30 at 2](https://user-images.githubusercontent.com/15604962/62117117-f6837080-b2d8-11e9-9af5-b05132d151c1.png)

**Comment by nartc** [comment]
@emjimadhu Can you share your whole base.service.ts ?
